#!/usr/bin/env python3
"""Generate the PS2 Library UI bitmap-glyph atlas.

Rasterizes a UI font (Inter by default) into 8-bit coverage glyphs at the
exact pixel heights the frontend uses, then emits ui_font.hpp / ui_font.cpp.
Run offline; the output is checked in.
"""
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
MAIN = HERE / "src" / "main.cpp"
FONT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"C:\Users\spkro\AppData\Local\Temp\opencode\fonts\inter\extras\ttf\Inter-Regular.ttf")
OUT_HPP = HERE.parent / "native-menu-probe-02" / "src" / "ui_font.hpp"
OUT_CPP = HERE.parent / "native-menu-probe-02" / "src" / "ui_font.cpp"
LINE_ROWS = 7  # the old bitmap font was 7 rows tall; text(scale) => 7*scale px


def text_scales(source: str):
    """Return the set of integer scale values passed as canvas.text's 4th arg."""
    scales = set()
    for m in re.finditer(r"canvas\.text\(", source):
        i = m.end()
        depth = 1
        args, cur = [], ""
        in_str, in_chr, esc = False, False, False
        while i < len(source) and depth > 0:
            c = source[i]
            if in_str:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == '"':
                    in_str = False
                cur += c
            elif in_chr:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == "'":
                    in_chr = False
                cur += c
            elif c == '"':
                in_str = True
                cur += c
            elif c == "'":
                in_chr = True
                cur += c
            elif c == "(":
                depth += 1
                cur += c
            elif c == ")":
                depth -= 1
                if depth == 0:
                    args.append(cur)
                    break
                cur += c
            elif c == "," and depth == 1:
                args.append(cur)
                cur = ""
            else:
                cur += c
            i += 1
        if len(args) >= 4 and re.fullmatch(r"\s*\d+\s*", args[3]):
            scales.add(int(args[3]))
    return sorted(scales)


def main():
    src = MAIN.read_text(encoding="utf-8")
    scales = text_scales(src)
    print("scales used:", scales)
    font_path = str(FONT)
    chars = [chr(c) for c in range(0x20, 0x7F)]

    hpp = []
    hpp.append("// Generated by gen_sst_font.py from the UI font. Do not edit.")
    hpp.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    hpp.append("#pragma once")
    hpp.append("#include <cstddef>")
    hpp.append("#include <cstdint>")
    hpp.append("namespace ui_font {")
    hpp.append("struct Glyph {")
    hpp.append("    char ch;")
    hpp.append("    std::int8_t x0, y0;")
    hpp.append("    std::uint8_t w, h, advance;")
    hpp.append("    std::uint32_t offset;")
    hpp.append("};")
    hpp.append("struct Face {")
    hpp.append("    unsigned pixel_height;")
    hpp.append("    unsigned count;")
    hpp.append("    const Glyph* glyphs;")
    hpp.append("    const std::uint8_t* pixels;")
    hpp.append("};")
    hpp.append("const Face* face_for(unsigned pixel_height) noexcept;")
    hpp.append("const Glyph* glyph(const Face& face, char ch) noexcept;")
    hpp.append("} // namespace ui_font")

    cpp = []
    cpp.append("// Generated by gen_sst_font.py from the UI font. Do not edit.")
    cpp.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    cpp.append('#include "ui_font.hpp"')
    cpp.append("namespace ui_font {")
    cpp.append("namespace {")

    face_entries = []
    total_bytes = 0
    for s in scales:
        pixel_height = LINE_ROWS * s
        font = ImageFont.truetype(font_path, pixel_height)
        ascent, descent = font.getmetrics()
        line_height = ascent + descent
        pool = bytearray()
        glyph_rows = []
        for ch in chars:
            canvas = Image.new("L", (pixel_height * 2 + 8, line_height + 4), 0)
            draw = ImageDraw.Draw(canvas)
            draw.text((pixel_height // 2, 2 + ascent), ch, font=font, fill=255, anchor="ls")
            bbox = canvas.getbbox()
            advance = int(round(font.getlength(ch)))
            if bbox is None:
                glyph_rows.append((ch, 0, 0, 0, 0, advance, len(pool)))
                continue
            left, top, right, bottom = bbox
            w, h = right - left, bottom - top
            alpha = canvas.crop(bbox).tobytes()
            pool.extend(alpha)
            x0 = left - (pixel_height // 2)
            y0 = top - 2
            glyph_rows.append((ch, x0, y0, w, h, advance, len(pool) - len(alpha)))
        name = f"face_{s}"
        cpp.append(f"const std::uint8_t {name}_pixels[] = {{")
        line = "    "
        for i, b in enumerate(pool):
            line += f"{b},"
            if len(line) > 200:
                cpp.append(line)
                line = "    "
        if line.strip():
            cpp.append(line)
        cpp.append("};")
        cpp.append(f"const Glyph {name}_glyphs[] = {{")
        for (ch, x0, y0, w, h, adv, off) in glyph_rows:
            esc = "\\\\" if ch == "\\" else ("\\'" if ch == "'" else ch)
            cpp.append(
                f"    {{'{esc}', {x0}, {y0}, {w}, {h}, {adv}, {off}}},"
            )
        cpp.append("};")
        face_entries.append((pixel_height, len(chars), name))
        total_bytes += len(pool)

    cpp.append("const Face faces[] = {")
    for (ph, count, name) in face_entries:
        cpp.append(f"    {{{ph}, {count}, {name}_glyphs, {name}_pixels}},")
    cpp.append("};")
    cpp.append("constexpr std::size_t face_count = sizeof(faces) / sizeof(faces[0]);")
    cpp.append("} // namespace")
    cpp.append("")
    cpp.append("const Face* face_for(unsigned pixel_height) noexcept {")
    cpp.append("    if (pixel_height == 0) return faces;")
    cpp.append("    const Face* best = faces;")
    cpp.append("    unsigned best_delta = 0xFFFFFFFFu;")
    cpp.append("    for (std::size_t i = 0; i < face_count; ++i) {")
    cpp.append("        const unsigned delta = faces[i].pixel_height > pixel_height")
    cpp.append("            ? faces[i].pixel_height - pixel_height")
    cpp.append("            : pixel_height - faces[i].pixel_height;")
    cpp.append("        if (delta < best_delta) { best_delta = delta; best = &faces[i]; }")
    cpp.append("    }")
    cpp.append("    return best;")
    cpp.append("}")
    cpp.append("")
    cpp.append("const Glyph* glyph(const Face& face, char ch) noexcept {")
    cpp.append("    const Glyph* fallback = &face.glyphs[0];")
    cpp.append("    for (unsigned i = 0; i < face.count; ++i) {")
    cpp.append("        if (face.glyphs[i].ch == ch) return &face.glyphs[i];")
    cpp.append("        if (face.glyphs[i].ch == '?') fallback = &face.glyphs[i];")
    cpp.append("    }")
    cpp.append("    return fallback;")
    cpp.append("}")
    cpp.append("} // namespace ui_font")

    OUT_HPP.write_text("\n".join(hpp) + "\n", encoding="utf-8")
    OUT_CPP.write_text("\n".join(cpp) + "\n", encoding="utf-8")
    print(f"wrote {OUT_HPP.name} ({OUT_HPP.stat().st_size} bytes) and "
          f"{OUT_CPP.name} ({OUT_CPP.stat().st_size} bytes); alpha pool {total_bytes} bytes")


if __name__ == "__main__":
    main()
