#!/usr/bin/env python3
"""Generate the button-icon atlas for the PS2 Library UI.

Rasterizes the (white) DualSense prompt PNGs into 8-bit coverage bitmaps and
emits ui_icons.hpp / ui_icons.cpp. Run offline; the output is checked in.
"""
import sys
from pathlib import Path

from PIL import Image

SRC = Path(
    sys.argv[1]
    if len(sys.argv) > 1
    else r"/mnt/c/Users/spkro/Desktop/PS2 FTP Iso Loader/PS5 Button Icons and Controls/PS5 Button Icons and Controls/Buttons Solid/White/256w"
)
OUT_HPP = (
    Path(__file__).resolve().parent.parent / "native-menu-probe-02" / "src" / "ui_icons.hpp"
)
OUT_CPP = (
    Path(__file__).resolve().parent.parent / "native-menu-probe-02" / "src" / "ui_icons.cpp"
)
HEIGHT = 28
ICONS = [
    ("cross", "Cross.png"),
    ("circle", "Circle.png"),
    ("triangle", "Triangle.png"),
    ("square", "Square.png"),
    ("dpad_up", "D-Pad Up.png"),
    ("dpad_down", "D-Pad Down.png"),
    ("dpad_left", "D-Pad Left.png"),
    ("dpad_right", "D-Pad Right.png"),
    ("l1", "L1.png"),
    ("r1", "R1.png"),
    ("options", "Options.png"),
    ("create", "Create.png"),
    ("home", "Home.png"),
    ("discord", "/mnt/c/Users/spkro/AppData/Local/Temp/opencode/fonts/brand/discord.png"),
    ("x", "/mnt/c/Users/spkro/AppData/Local/Temp/opencode/fonts/brand/x.png"),
]


def main():
    pool = bytearray()
    entries = []
    for name, filename in ICONS:
        path = Path(filename)
        if not path.is_absolute():
            path = SRC / filename
        im = Image.open(path).convert("RGBA")
        scale = HEIGHT / im.height
        w = max(1, round(im.width * scale))
        im = im.resize((w, HEIGHT), Image.LANCZOS)
        alpha = im.getchannel("A")
        data = alpha.tobytes()
        entries.append((name, w, HEIGHT, len(pool)))
        pool.extend(data)

    hpp = []
    hpp.append("// Generated by gen_ui_icons.py. Do not edit.")
    hpp.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    hpp.append("#pragma once")
    hpp.append("#include <cstdint>")
    hpp.append("namespace ui_icons {")
    hpp.append("enum class Id : unsigned {")
    hpp.append("    " + ", ".join(entry[0] for entry in entries) + ",")
    hpp.append("    count,")
    hpp.append("};")
    hpp.append("struct Bitmap {")
    hpp.append("    std::uint8_t w, h;")
    hpp.append("    std::uint32_t offset;")
    hpp.append("};")
    hpp.append("inline constexpr unsigned pixel_height = %d;" % HEIGHT)
    hpp.append("const Bitmap* bitmaps() noexcept;")
    hpp.append("const std::uint8_t* pixels() noexcept;")
    hpp.append("} // namespace ui_icons")

    cpp = []
    cpp.append("// Generated by gen_ui_icons.py. Do not edit.")
    cpp.append("// SPDX-License-Identifier: GPL-3.0-or-later")
    cpp.append('#include "ui_icons.hpp"')
    cpp.append("namespace ui_icons {")
    cpp.append("namespace {")
    cpp.append("const std::uint8_t coverage[] = {")
    line = "    "
    for byte in pool:
        line += f"{byte},"
        if len(line) > 200:
            cpp.append(line)
            line = "    "
    if line.strip():
        cpp.append(line)
    cpp.append("};")
    cpp.append("const Bitmap table[] = {")
    for name, w, h, off in entries:
        cpp.append(f"    {{{w}, {h}, {off}}}, // {name}")
    cpp.append("};")
    cpp.append("} // namespace")
    cpp.append("const Bitmap* bitmaps() noexcept { return table; }")
    cpp.append("const std::uint8_t* pixels() noexcept { return coverage; }")
    cpp.append("} // namespace ui_icons")

    OUT_HPP.write_text("\n".join(hpp) + "\n", encoding="utf-8")
    OUT_CPP.write_text("\n".join(cpp) + "\n", encoding="utf-8")
    print(f"wrote {OUT_HPP.name} and {OUT_CPP.name}; {len(entries)} icons, pool {len(pool)} bytes")


if __name__ == "__main__":
    main()
