// Generated by gen_sst_font.py from the UI font. Do not edit.
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
#include <cstddef>
#include <cstdint>
namespace ui_font {
struct Glyph {
    char ch;
    std::int8_t x0, y0;
    std::uint8_t w, h, advance;
    std::uint32_t offset;
};
struct Face {
    unsigned pixel_height;
    unsigned count;
    const Glyph* glyphs;
    const std::uint8_t* pixels;
};
const Face* face_for(unsigned pixel_height) noexcept;
const Glyph* glyph(const Face& face, char ch) noexcept;
} // namespace ui_font
