// Generated by gen_ui_icons.py. Do not edit.
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
#include <cstdint>
namespace ui_icons {
enum class Id : unsigned {
    cross, circle, triangle, square, dpad_up, dpad_down, dpad_left, dpad_right, l1, r1, options, create, home, discord, x,
    count,
};
struct Bitmap {
    std::uint8_t w, h;
    std::uint32_t offset;
};
inline constexpr unsigned pixel_height = 28;
const Bitmap* bitmaps() noexcept;
const std::uint8_t* pixels() noexcept;
} // namespace ui_icons
